### PR TITLE
deploy latest version of 1ca9d4de6743798fd56f8958d6ce09f2dde85b09

### PR DESCRIPTION
**Pull request by GabrielBuragev**
Website v2 deployment

### CODE REVIEW

**Comment by manuelwedler** [comment]
In the past we did not use pull requests for the deployments of the website. We just pushed the build to the gh-pages branch directly. In my opinion it does not make sense to review the bundle, as it is just generated code. What do you think?

**Comment by GabrielBuragev** [comment]
The main reason why i created this PR is to tag it inside [this epic](https://github.com/beamer-bridge/beamer/issues/1031) and for simplifying the deployment when the day for the launch comes.

Yeah, in this case i just added you as a reviewer so you can also double check, when opening it via a local web server, that the changes are really going to be reflected when this branch gets merged. Since the changes are pretty drastic its easy to review this with a local instance, otherwise it doesn't make sense. 
Also, since its my first time pushing to the gh-pages branch here, wanted to make sure i am not making a mistake somewhere.

For the next deployments i will just skip the review process.

**Comment by manuelwedler** [comment]
We just talked about this personally and came to the conclusion that it makes sense that deployments are reviewed. A reviewer would only check if the built website works as expected by running it locally, not really reviewing the changes. This should be the process from now on.

**Review by manuelwedler — APPROVED** [review]
Tested it locally and looks good :)

**Comment by GabrielBuragev** [comment]
2 pairs of eyes is always better than one! :eyes:

**Pull request merged**
